version: '3.8'

services:
  app:
    build: .
    container_name: meine-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: meine-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=meinedb
      - POSTGRES_USER=meinuser
      - POSTGRES_PASSWORD=meinsicherespasswort
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: